set_lens_mask_state:
  name: "Set Lens Mask State"
  description: "Set Lens Mask State"
  fields:
    ipc_url:
      name: "IPC Url"
      description: "IPC Url"
      required: true
      default: "http://"
      example: "http://192.168.2.89"
      selector:
        text:
          type: url
    username:
      name: "Username"
      description: "Username"
      required: true
      default: "admin"
      example: "admin"
      selector:
        text:
    password:
      name: "Password"
      description: "Password"
      required: true
      selector:
        text:
          type: password
    lens_mask_state:
      name: "Lens Mask State"
      description: "Lens Mask State"
      required: true
      default: "off"
      example: "off"
      selector:
        select:
          options:
            - "off"
            - "on"
command:
  name: "Command"
  description: "Call Command"
  fields:
    ipc_url:
      name: "IPC Url"
      description: "IPC Url"
      required: true
      default: "http://"
      example: "http://192.168.2.89"
      selector:
        text:
          type: url
    username:
      name: "Username"
      description: "Username"
      required: true
      default: "admin"
      example: "admin"
      selector:
        text:
    password:
      name: "Password"
      description: "Password"
      required: true
      selector:
        text:
          type: password
    command:
      name: "Command"
      description: "Command"
      required: true
      default: ''
      selector:
        select:
          custom_value: true
          options:
            - '{"method":"do","preset":{"goto_preset": {"id": "1"}}}'
            - '{"method":"do","preset":{"set_preset":{"name":"name","save_ptz":"1"}}}'
            - '{"method":"do","motor":{"manual_cali":"null"}}'
            - '{"method":"set","led":{"config":{"enabled":"on"}}}'
            - '{"method":"set","lens_mask":{"lens_mask_info":{"enabled":"on"}}}'
            - '{"method":"do","msg_alarm":{"manual_msg_alarm":{"action":"start"}}}'
            - '{"method":"do","msg_alarm":{"manual_msg_alarm":{"action":"stop"}}}'
            - '{"method":"do","system":{"reboot":"null"}}'
            - '{"method":"get","video":{"name":["main","minor"]}}'
            - '{"method":"get","network":{"name":["wan_status"]}}'
            - '{"method":"get","system":{"name":["clock_status","sys"]}}'
            - '{"method":"get","device_info":{"name":["basic_info","info"]}}'
            - '{"method":"get","cloud_config":{"name":["new_firmware","upgrade_info","bind"]}}'
            - '{"method":"get","protocol":{"name":["wan","static","dhcp"]}}'
            - '{"method":"get","harddisk_manage":{"name":["harddisk","video","picture"],"table":["hd_info"]}}'
