set_lens_mask_state:
  name: "Set Lens Mask State"
  description: "Set Lens Mask State"
  fields:
    ipc_url:
      name: "IPC Url"
      description: "IPC Url"
      required: true
      default: "http://"
      example: "http://192.168.2.89"
      selector:
        text:
          type: url
    username:
      name: "Username"
      description: "Username"
      required: true
      default: "admin"
      example: "admin"
      selector:
        text:
    password:
      name: "Password"
      description: "Password"
      required: true
      selector:
        text:
          type: password
    lens_mask_state:
      name: "Lens Mask State"
      description: "Lens Mask State"
      required: true
      default: "off"
      example: "off"
      selector:
        select:
          options:
            - "off"
            - "on"
command:
  name: "Command"
  description: "Call Command"
  fields:
    ipc_url:
      name: "IPC Url"
      description: "IPC Url"
      required: true
      default: "http://"
      example: "http://192.168.2.89"
      selector:
        text:
          type: url
    username:
      name: "Username"
      description: "Username"
      required: true
      default: "admin"
      example: "admin"
      selector:
        text:
    password:
      name: "Password"
      description: "Password"
      required: true
      selector:
        text:
          type: password
    command:
      name: "Command"
      description: "Command"
      required: true
      default: ''
      example: '{"method":"set","lens_mask":{"lens_mask_info":{"enabled":"on"}}}'
      selector:
        text:
